project:
  type: website

toc: true
toc-expand: 2
number-sections: false

execute:
  freeze: auto

website:
  title: "ITS Propagation Library Wiki"
  twitter-card:
    card-style: summary
    description: |
      The NTIA/ITS Propagation Library: a versatile and robust set of
      tools for propagation modeling. Learn more on our wiki.
    image: images/ntia-logo-300px.png
    image-alt: National Telecommunications and Information Administration Logo
    image-width: 300
    image-height: 300
    creator: "@NTIA"
    site: "@NTIA"
  open-graph:
    description: |
      The NTIA/ITS Propagation Library: a versatile and robust set of
      tools for propagation modeling. Learn more on our wiki.
    image: images/ntia-logo-300px.png
    image-alt: National Telecommunications and Information Administration Logo
    image-width: 300
    image-height: 300
    locale: en_US
  site-url: https://ntia.github.io/propagation-library-wiki
  navbar:
    title: "ITS PropLib Wiki"
    left:
      - href: index.qmd
        text: Home
      - text: "U.S. Models"
        menu:
          - Coming Soon
      - text: "ITU-R Models"
        menu:
          - models/P2108/index.qmd
      - about.qmd
  google-analytics:
    tracking-id: G-48B5WEZDBS
    version: 4

format:
  html:
    page-layout: article
    toc: true
    toc-title: Contents
    code-fold: false
    theme: [cosmo, theme.scss]
    include-in-header: header.html
    include-after-body: 
      file: footer.html

jupyter: python3
bibliography: references.bib
csl: ieee.csl

quarto-required: ">= 1.4.555"