project:
  type: website
quarto-required: ">= 1.4.555"

website:
  title: "ITS Propagation Library Wiki"
  twitter-card:
    card-style: summary
    description: |
      The NTIA/ITS Propagation Library: a versatile and robust set of
      tools for propagation modeling. Learn more on our wiki.
    image: images/ntia-logo-300px.png
    image-alt: National Telecommunications and Information Administration Logo
    image-width: 300
    image-height: 300
    creator: "@NTIA"
    site: "@NTIA"
  open-graph:
    description: |
      The NTIA/ITS Propagation Library: a versatile and robust set of
      tools for propagation modeling. Learn more on our wiki.
    image: images/ntia-logo-300px.png
    image-alt: National Telecommunications and Information Administration Logo
    image-width: 300
    image-height: 300
    locale: en_US
  site-url: https://ntia.github.io/propagation-library-wiki
  navbar:
    title: "ITS PropLib Wiki"
    left:
      - href: index.qmd
        text: Home
      - text: "U.S. Models"
        menu:
          - Coming Soon
      - text: "ITU-R Models"
        menu:
          - models/P2108/index.qmd
      - about.qmd
  google-analytics:
    tracking-id: G-48B5WEZDBS
    version: 4

format:
  html:
    # Format/theme options
    theme: [cosmo, theme.scss]
    css: uswds/css/uswds.min.css  # Maybe compile from SASS instead?
    mainfont: $source-sans-pro    # Defined in theme.scss
    fontcolor: $semi-black        # Defined in theme.scss
    # Table of Contents
    toc: true
    toc-title: On this page
    tox-expand: true
    # Layout
    fig-cap-location: bottom
    tbl-cap-location: top
    page-layout: article
    # Code
    code-fold: false
    code-overflow: scroll
    code-copy: true
    # Figures
    fig-align: center
    fig-responsive: true
    # Links
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: .*ntia\.gov.*|.*ntia\.github.io.*|.*pages\.github.io.*
    # References
    bibliography: references.bib
    csl: ieee.csl
    # Includes
    include-in-header: header.html
    include-after-body: 
      file: footer.html

