project:
  type: website

toc: true
number-sections: false

execute:
  freeze: auto

website:
  title: "NTIA/ITS Propagation Library Wiki"
  navbar:
    title: "NTIA/ITS PropLib Wiki"
    left:
      - href: index.qmd
        text: Home
      - text: "U.S. Models"
        menu:
          - models/ITM/index.qmd
          - models/ITM-MidBand/index.qmd
      - text: "ITU-R Models"
        menu:
          - models/P2108/index.qmd
      - about.qmd

format:
  html:
    page-layout: article
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: Contents
    code-fold: false

jupyter: python3
bibliography: references.bib
csl: ieee.csl

quarto-required: ">= 1.5.40"