---
title: "Quick Start - Python"
date: 2024-06-11
date-modified: 2024-06-11
---

{{< include /includes/_under_construction.qmd >}}

This page provides a walkthrough on how to quickly get up and running installing and running ITS PropLib software in a Python development environment.

## Dependencies and Limitations

Users are assumed to be using a [current version](https://devguide.python.org/versions/) of Python 3. All officially-released versions of Python which have not reached end-of-life are supported. Package dependencies are defined on a per-package basis in each project's `pyproject.toml` file, which will allow your package manager (e.g., `pip`) to discover and install required dependencies automatically when you install a PropLib package.

## Getting Packages
::: {.callout-warning}
### TO DO

Update this section when packages are available on PyPi
:::

# Quick Start

This example walks a user through how to install and call into ITM.

## Installing Packages
::: {.callout-warning}
### TO DO

Modify example to avoid use of `conda`
:::

Create a new conda environment:

```cmd
conda create --name prop
conda activate prop
```

Install `numpy` as it's a dependency of the `itm` package

```cmd
pip install numpy
```
or
```cmd
conda install -c anaconda numpy
```

Install `pythonnet` as it's a dependency of the `ohiopyle` package
```cmd
pip install -i https://pypi.anaconda.org/pythonnet/simple pythonnet
```
or
```cmd
conda install -c pythonnet pythonnet=2.5.2
```

Install `itm` from the local repository

```cmd
pip install itm --no-index --find-links file://itsfs01/Tools/Python/pip
```

Install `ohiopyle` from the local repository
```cmd
pip install ohiopyle --no-index --find-links file://itsfs01/Tools/Python/pip
```

## Calling PropCore in Python

::: {.callout-warning}
### TO DO

Replace with an interactive Jupyter example
:::

Open Spyder (or your Python IDE of choice) and copy the following snippet of code:

```python
import itm

# define the terrain profile in PFL format
pfl = [5, 200, 5, 7, 2, 4, 7, 5]

# define link parameters
f__mhz = 3500;                      # MHz
h_tx__meter = 10                    # meters, AGL
h_rx__meter = 5                     # meters, AGL
N_0 = 301                           # N-Units
epsilon = 15                        # average ground
sigma = 0.005                       # average ground
climate = itm.Climate.ContinentalTemperate
pol = itm.Polarization.Horizontal

# define variability parameters
mdvar = 13
time = 50                           # median
location = 50                       # median
situation = 50                      # median

# call ITM
rtn, A__db, warnings, ivals = itm.ITM_P2P_TLS(h_tx__meter, h_rx__meter, 
    pfl, climate, N_0, f__mhz, pol, epsilon, sigma, mdvar, 
    time, location, situation)

assert(rtn == 0)                    # no errors
assert(A__db == 105.85899333756423) # basic transmission loss, in dB
assert(warnings == 0)               # no warnings

# can use the intermediate values object to access additional information
# from the ITM prediction
print(f"The mode of propagation is {ivals.mode.name}")
print(f"The effective height of the TX is {ivals.h_e__meter[0]} meters.")
print(f"The free space basic transmission loss is {ivals.A_fs__db} dB.")
# The mode of propagation is LineOfSight
# The effective height of the TX is 10.222222222222221 meters.
# The free space basic transmission loss is 103.33136088700552 dB.
```