---
title: "ITU-R P.2108"
date: 2024-06-28
date-modified: 2024-06-28
---

Recommendation ITU-R P.2108 _Prediction of clutter loss_ contains three methods for the prediction of clutter loss: the [Height Gain Terminal Correction Model](#height-gain-terminal-correction-model), [Terrestrial Statistical Model](#terrestrial-statistical-model), and [Aeronautical Statistical Model](#aeronautical-statistical-model) [@p2108-1, Sections 3.1-3.3]. This software implements each of the three models.

{{< include /includes/_getting_started.qmd >}}

## Model Selection

Selection and use of the appropriate model is required to obtain meaningful outputs. Refer to Table 1 from @p2108-1 [Section 2] for a summary of the applicable scenarios for each model. Further details about the applicability and assumptions of each of the P.2108 models are available in the sections of the Recommendation in which they are described.

## Functions

### Height Gain Terminal Correction Model

The height gain terminal correction model is described in @p2108-1 [Section 3.1]. This model calculates an additional loss, $A_h$, which can be added to the basic transmission loss of a path calculated above the clutter. Therefore basic transmission loss should be calculated to/from the height of the representative clutter height used. This model can be applied to both transmitting and receiving ends of the path.


| Variable       | Type   | Units | Limits               | Description                       |
|----------------|--------|-------|----------------------|-----------------------------------|
| `f__ghz`       | double | GHz   | $0.03 \leq f \leq 3$ | Frequency                         |
| `h__meter`     | double | meter | $0 \leq h$           | Antenna height                    |
| `w_s__meter`   | double | meter | $0 < w_s$            | Street width                      |
| `R__meter`     | double | meter | $0 < R$              | Representative clutter height     |
| `clutter_type` | `ClutterType` enum | N/A | enum       | See @tbl-p2108-3p1-clutter-types  |
: Inputs for the height gain terminal correction model {#tbl-p2108-3p1-inputs}

The values for $w_s$ and $R$ should be set based upon local information. If local information is not available, @p2108-1 [Section 3.1.1] defines appropriate default values: $w_s=27$ and a set of values for $R$ based on the clutter type, which are reproduced in @tbl-p2108-3p1-clutter-types.
This table also provides the integer values mapped to each clutter type in the enumeration objects are provided by the software for ease of use.

| Clutter Type | Enum Value | Default $R$ (m) |
|--------------|:----------:|-----------------|
| Water/sea    |          1 |              10 |
| Open/rural   |          2 |              10 |
| Suburban     |          3 |              10 |
| Urban        |          4 |              15 |
| Trees/forest |          5 |              15 |
| Dense urban  |          6 |              20 |
: Clutter types for the @p2108-1 [Section 3.1] model {#tbl-p2108-3p1-clutter-types}

{{< include /includes/_code_examples.qmd >}}

[C++](cpp.qmd#height-gain-terminal-correction-model){.btn .btn-secondary role="button"}
[C#/.NET](dotnet.qmd#height-gain-terminal-correction-model){.btn .btn-secondary disabled role="button"}
[MATLAB](matlab.qmd#height-gain-terminal-correction-model){.btn .btn-secondary disabled role="button"}
[Python](python.qmd#height-gain-terminal-correction-model){.btn .btn-secondary role="button"}

### Terrestrial Statistical Model

The terrestrial statistical model is described in @p2108-1 [Section 3.2]. The model can be applied for urban and suburban environments provided terminal heights are well below the clutter height. The correction produced by this model can be applied at one terminal, or, if the path length is at least 1 km, at both terminals.

This model calculates an additional loss, $L_{ctt}$, which can be added to the transmission loss or basic transmission loss. As this is a statistical model, the term $L_{ctt}$ is the clutter loss not exceeded for $p$ percent of locations for a terrestial path of length $d$. If the transmission loss or basic transmission loss has been calculated using a model that inherently accounts for clutter over the entire path then this model should not be applied.

| Variable | Type   | Units | Limits               | Description   |
|----------|--------|-------|----------------------|---------------|
| `f__ghz` | double | GHz   | $0.5 \leq f \leq 67$ | Frequency     |
| `d__km`  | double | km    | $0.25 \leq d$ | Path distance. Must be $\geq 1$ km to apply the correction at both ends of the path. |
| `p`      | double | %     | $0 < p < 100$ | Percentage of locations at which predicted clutter loss will not be exceeded         |
: Inputs for the terrestrial statistical model {#tbl-p2108-3p2-inputs}

{{< include /includes/_code_examples.qmd >}}

[C++](cpp.qmd#terrestrial-statistical-model){.btn .btn-secondary .btn role="button"}
[C#/.NET](dotnet.qmd#terrestrial-statistical-model){.btn .btn-secondary .btn disabled role="button"}
[MATLAB](matlab.qmd#terrestrial-statistical-model){.btn .btn-secondary disabled .btn role="button"}
[Python](python.qmd#terrestrial-statistical-model){.btn .btn-secondary .btn role="button"}

### Aeronautical Statistical Model

The Earth-space and aeronautical statistical clutter loss model is described in @p2108-1 [Section 3.3]. This model is applicable when one terminal is within man-made clutter and the other is a satellite, aeroplane, or other platform above the surface of the Earth. The model is applicable to urban and suburban clutter environments.

This model calculates an additional loss, $L_{ces}$, which can be added to the basic transmission loss of a path calculated. As this is a statistical model, the term $L_{ces}$ is the clutter loss not exceeded for $p$ percent of locations.

The method used to develop this model is described in @p2402-0.

| Variable      | Type   | Units  | Limits                  | Description     |
|---------------|--------|--------|-------------------------|-----------------|
| `f__ghz`      | double | GHz    | $10 \leq f \leq 100$    | Frequency       |
| `theta__deg`  | double | degree | $0 \leq \theta \leq 90$ | Elevation angle |
| `p`           | double | %      | $0 < p < 100$           | Percentage of locations at which predicted clutter loss will not be exceeded |
: Inputs for the aeronautical statistical model {#tbl-p2108-3p3-inputs}

{{< include /includes/_code_examples.qmd >}}

[C++](cpp.qmd#aeronautical-statistical-model){.btn .btn-secondary .btn role="button"}
[C#/.NET](dotnet.qmd#aeronautical-statistical-model){.btn .btn-secondary .btn disabled role="button"}
[MATLAB](matlab.qmd#aeronautical-statistical-model){.btn .btn-secondary .btn disabled role="button"}
[Python](python.qmd#aeronautical-statistical-model){.btn .btn-secondary .btn role="button"}