---
title: "ITU-R P.2108 - MATLAB"
---
::: {.callout-warning}
## Page Under Construction

This page is still under construction and has not yet been finalized. Information may be outdated, incorrect, or missing. While this message is visible, contact [code@ntia.gov](mailto:code@ntia.gov) with any questions.
:::

The package name to install is `p2108`.  The package can be found in the matpak repo with the following command:

```
matpak search p2108
```

## Installing Package

Use the following command to install `p2108` from the matpak repo:

```
matpak install p2108
```

The packag can be installed directly into your working directory or in a seperate directory that you include in your execution path.

## Documentation

All `p2108` functions are docummented with detailed headers, such as:

```matlab
% Function AeronauticalStatisticalModel(...)
%
% Description: The Earth-space and aeronautical statistical 
%       clutter loss model as described in Section 3.3.
%
% Inputs:
%   f__ghz : Frequency, in GHz
%   theta__deg : Elevation angle, in degrees
%   p : Percentange of locations, in %
%
% Outputs:
%   L_ces__db : Additional loss (clutter loss), in dB
%   rtn : P2108 return value
```

# Examples

## Height Gain Terminal Correction Model

```matlab
% define inputs
f__ghz = 1;         % GHz
h__meter = 1.5;     % meters
w_s__meter = 27;    % meters (default value)
R__meter = 20;      % meters (Dense urban default value)
clutter_type = 6;   % Dense urban

% call clutter model
[A_h__db, rtn] = P2108.HeightGainTerminalCorrectionModel(...
    f__ghz, h__meter, w_s__meter, R__meter, clutter_type)
% A_h__db = 8.7694
% rtn = 0

% can also use clutter type enum
clutter_type = P2108ClutterType.DenseUrban;

% call clutter model
[A_h__db, rtn] = P2108.HeightGainTerminalCorrectionModel(...
    f__ghz, h__meter, w_s__meter, R__meter, clutter_type)
% A_h__db = 8.7694
% rtn = 0
```

## Terrestrial Statistical Model

```matlab
% define inputs
f__ghz = 3;         % GHz
d__km = 0.5;        % km
p = 50;             % %

% call clutter model
[L_ctt__db, rtn] = P2108.TerrestrialStatisticalModel(...
    f__ghz, d__km, p)
% L_ctt__db = 26.1008
% rtn = 0
```

## Aeronautical Statistical Model

```matlab
% define inputs
f__ghz = 15;        % GHz
theta__deg = 10;    % degrees
p = 50;             % %

% call clutter model
[L_ces__db, rtn] = P2108.AeronauticalStatisticalModel(...
    f__ghz, theta__deg, p)
% L_ces__db = 14.3337
% rtn = 0
```
