---
title: "The Recommendation ITU-R P.676-12 – C++"
date: 2024-12-02
date-modified: 2025-06-12
---

This page details the installation and usage of the C++ version of the PropLib implementation of the Recommendation ITU-R P.676-12.

{{< include /includes/_link_to_model_home.qmd >}}

## Installation

To use the C++ library in your code, you'll need to download the shared library (`.dll` on Windows, `.dylib` on macOS, or `.so` on Linux) and the header file. These are distributed for each supported platform as part of the [GitHub Releases](https://github.com/NTIA/p676/releases/) starting with v1.1. Prior to v1.1, support was only provided for Windows platforms.

To use the shared library in your project, you'll need to link against it. The details for this process differ depending on your compiler and/or IDE, but generally you will need to somehow provide the path to the files you downloaded from the GitHub release.

Once you've linked the dynamic library to your project, all you need to do is include the appropriate header file and, optionally, use its namespace:

```cpp
#include "P676.h"

using namespace ITS::ITU::PSeries::P676;  // Optional: makes later code more concise
```

This library has no external C++ dependencies.

{{< include /includes/cpp/_documentation.qmd >}}

[Docs](https://ntia.github.io/p676){.btn .btn-secondary .btn role="button"}

## Examples

The following code example shows how each of the three major methods from the Recommendation ITU-R P.676 can be called in a C++ program.

### Specific Attenuation Model

```cpp
#include "P676.h"
using namespace ITS::ITU::PSeries::P676;

int main() {
    // Define inputs
    double f__ghz = 60.0;       // Frequency, in GHz
    double T__kelvin = 288.15;  // Temperature, in Kelvin
    double e__hPa = 9.97288879; // Water vapour partial pressure, in hPa
    double p__hPa = 1013.25;    // Dry air pressure, in hPa

    // Create variables to store outputs
    double gamma;   // Specific gaseous attenuation, in dB/km

    // Call Specific Attenuation Model
    gamma = SpecificAttenuation(f__ghz, T__kelvin, e__hPa, p__hPa);

    // gamma is approx. 14.7783
}
```

### Terrestrial Path Attenuation Model

```cpp
#include "P676.h"
using namespace ITS::ITU::PSeries::P676;

int main() {
    // Define inputs
    double f__ghz = 26.0;       // Frequency, in GHz
    Atmosphere atmosphere = Atmosphere::
        ATMOSPHERE__MAGRA;      // Reference atmosphere from P.835, enum
    double r_0__km = 10.5;      // Path length, in km

    // Create variables to store outputs
    double A_gas;       // Gaseous attenuation, in dB
    ReturnCode rtn;     // Return code

    // Call Terrestrial Path Attenuation Model
    rtn = TerrestrialPathAttenuation(f__ghz, atmosphere, r_0__km, A_gas);

    // rtn is 0 (SUCCESS)
    // A_gas is approx. 1.3128
}
```

### Slant Path Attenuation Model

```cpp
#include "P676.h"
using namespace ITS::ITU::PSeries::P676;

int main() {
    // Define inputs
    double f__ghz = 48.0;       // Frequency, in GHz
    double h_1__km = 10;        // Height of the low terminal, in km
    double h_2__km = 95;        // Height of the high terminal, in km
    double beta_1__rad = 0.75;  // Elevation angle (from zenith), in rad
    Atmosphere atmosphere = Atmosphere::
        ATMOSPHERE__HIGH_LAT_WINTER;    // Reference atmosphere from P.835, enum
    
    // Create variables to store outputs
    SlantPathAttenuationResult result;  // Slant path result structure
    ReturnCode rtn;     // Return code

    // Call Slant Path Attenuation Model
    rtn = SlantPathAttenuation(f__ghz, h_1__km, h_2__km, beta_1__rad, atmosphere, result);

    // rtn is 0 (SUCCESS)
    // result.A_gas__db	is approx. 0.1014 dB
    // bending__rad is approx. 8.0309e-05 rad
    // a__km is approx. 115.5221 km
    // incident__rad is approx. 0.7379 rad
    // delta_L__km is approx. 0.0008058 km
}
```