---
title: "Low Frequency / Medium Frequency Propagation Model"
date: 2024-12-02
date-modified: 2025-06-12
---

The Low Frequency / Medium Frequency (LF/MF) propagation model predicts basic transmission loss in the frequency range 0.01 - 30 MHz for propagation paths over a smooth Earth and antenna heights less than 50 meters. [@ntia-tr-99-368]

{{< include /includes/_getting_started.qmd >}}

## Model Background

This model fundamentally predicts basic transmission loss using @eq-lfmf-btl.

$$
\begin{align}
\text{BTL (dB)} =&\ 10\log(P_{tx} \cdot G_{tx}) + 10\log(\eta_0) + 20\log(f) \\
&-20\log(E_{gw}) - 20\log(c)
\end{align}
$$ {#eq-lfmf-btl}

In @eq-lfmf-btl, $P_{tx}$ and $f$ are model inputs, where $P_{tx}$ is in watts and $f$ has been converted to hertz. The constants $\eta_0$ and $c$ are the impedance of free space and the speed of light in vacuum, respectively. $G_{tx}$ is the linear conversion of the transmitter antenna gain, which is set to 4.77 dBi. This factor is included to remove the impacts of an equivalent scaling factor which is used when calculating the ground wave. Finally, $E_{gw}$ is the internally-computed ground wave field strength, in volts per meter.

This smooth earth model implements two different methods to compute the ground wave, depending on the path distance and frequency. A cutoff distance for the use of the flat earth approximation is determined using the method described in the ITU-R Ground Wave Propagation handbook [@itu-r-sg3-ground-wave-handbook, pp. 7]. Up to this distance, a flat-Earth approximation with curvature correction is used [@ntia-tr-99-368, pp. 13; @wait-radiation-from-vertical-antenna]. Beyond this distance,  the ground wave strength is calculated by evaluating the full-wave theory integral using the residue series.

The model additionally outputs the predicted electric field strength of the ground wave, the received power, and the method used to calculate the ground wave.

## Functions

### Low Frequency / Medium Frequency (LF/MF) Propagation Model

This model's functionality is exposed through a single function. The inputs for this function are shown below in @tbl-lfmf-inputs.
The model outputs are provided in @tbl-lfmf-outputs.

| Variable      | Type   | Units  | Limits                  | Description                  |
|---------------|--------|--------|-------------------------|------------------------------|
| `h_tx__meter` | double | meter  | $0 \leq h_{tx} \leq 50$ | Height of the transmitter    |
| `h_rx__meter` | double | meter  | $0 \leq h_{rx} \leq 50$ | Height of the receiver       |
| `f__mhz`      | double | MHz    | $0.01 \leq f \leq 30$   | Frequency                    |
| `P_tx__watt`  | double | watt   | $0 < P_{tx}$            | Transmitter power            |
| `N_s`         | double | N-Unit | $250 \leq N_s \leq 400$ | Surface refractivity         |
| `d__km`       | double | kilometer | $0 < d$              | Path distance                |
| `epsilon`     | double | none   | $1 \leq \epsilon$       | Relative permittivity        |
| `sigma`       | double | siemens per meter | $0 < \sigma$ | Conductivity                 |
| `pol`         | `Polarization` enum | N/A | enum          | See @tbl-lfmf-polarizations  | 
: Inputs for the LF/MF model {#tbl-lfmf-inputs}

The `pol` input must be one of the two valid supported polarization types, as defined in @tbl-lfmf-polarizations.

| Enum Value | Polarization |
|------------|--------------|
| 0          | Horizontal   |
| 1          | Vertical     |
: Allowed polarization values for the LF/MF model {#tbl-lfmf-polarizations}

The LF/MF model produces an output which contains four values. These results indicate the predicted basic transmission loss, the ground wave electric field strength, the received power and the solution method used to calculate the ground wave.

| Variable    | Type    | Units             | Description             |
|-------------|---------|-------------------|-------------------------|
| `A_btl__db` | double  | dB                | Basic transmission loss |
| `E_dBuVm`   | double  | dB(μV/m)          | Electric field strength |
| `P_rx__dbm` | double  | dBm               | Received power          |
| `method`    | `SolutionMethod` enum | N/A | Solution method; see @tbl-lfmf-solution-methods |
: Outputs of the LF/MF model {#tbl-lfmf-outputs}

The `method` output indicates the solution method used internally by the model while generating the other outputs. The possible returned values are provided in @tbl-lfmf-solution-methods.

| Enum Value | Solution Method                  |
|------------|----------------------------------|
| 0          | Flat earth with curve correction |
| 1          | Residue series                   |
: Possible solution methods used by the LF/MF model {#tbl-lfmf-solution-methods}

{{< include /includes/_code_examples.qmd >}}

[C++](cpp.qmd#calling-the-lfmf-model){.btn .btn-secondary .btn role="button"}
[.NET](dotnet.qmd#calling-the-lfmf-model){.btn .btn-secondary .btn role="button"}
[MATLAB](matlab.qmd#calling-the-lfmf-model){.btn .btn-secondary .btn role="button"}
[Python](python.qmd#calling-the-lfmf-model){.btn .btn-secondary .btn role="button"}