on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - CONTRIBUTING.md
      - README.md
      - LICENSE.md

name: Render and Publish

permissions:
  contents: write
  pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
        
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install jupyter

    - name: Render Quarto Project
      if: ${{ github.event_name == 'pull_request' }}
      uses: quarto-dev/quarto-actions/render@v2
      with:
        to: html

    - name: Publish to GitHub Pages
      if: ${{ github.event_name == 'push' }}
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
